# Controls deployment options
[deployment]
    host = "127.0.0.1"
    port = 8000

    # Amount of worker Priviblur instances to spawn. Increases speed significantly.
    # workers = 1

    # # If you're running Priviblur behind a remote proxy, one or more of the following must be set
    # # can also be set via env variables by captialzing and prefixing with PRIVIBLUR_
    # #
    # # For more information see
    # # https://sanic.dev/en/guide/advanced/proxy-headers.html
    # #
    # # Default: None
    # #
    # forwarded_secret =
    # real_ip_header =
    # proxies_count =

# Controls redis cache options
# Ignore to disable the cache
#
# [cache]
    # url =

    # Number of seconds to cache poll results from active polls
    # cache_active_poll_results_for = 3600

    # Number of seconds to cache poll results from expired polls
    # cache_expired_poll_results_for = 86400

    # Number of seconds to cache feed (explore, search, etc) results for
    # cache_feed_for = 3600

    # Number of seconds to cache blog feed (blog posts, blog search, blog tagged posts, etc) results for
    # cache_blog_feed_for = 3600

    # Number of seconds to cache individual posts for
    # cache_blog_post_for = 300

# Controls behaviors pertaining to the way Priviblur requests Tumblr
# [priviblur_backend]
    # # Timeout for requests to Tumblr's API
    # main_response_timeout = 10

    # # Timeout for fetching image responses from Tumblr 
    # image_response_timeout = 30


# Controls logging behavior
#
# Use Python's numerical logging levels
# https://docs.python.org/3/howto/logging.html#logging-levels
# [logging]
    # # Sanic (Server)'s logging level'
    # sanic_logging_level = 30

    # # Priviblur's logging level
    # priviblur_logging_level = 30

    # # Priviblur extractor's logging level
    # priviblur_extractor_logging_level = 20


# [misc]
    # # Enable sanic's dev mode
    # dev_mode = false